@startuml
package "src_solution/abu/tcb" {
  [safety]
  [event_log]
  [security_monitor]
}
package "src_solution/abu/other" {
  [pseudo_ai]
  [numpy_workflow]
  [domain_process]
}
[security_monitor] --> [domain_process]
@enduml
